export const EMAIL_FIELD = 'emailField';
export const EMAIL_BLANK_VALIDATION_MSG = 'Please enter your email id';
export const EMAIL_REGEX_VALIDATION_MSG = 'Please enter a valid email';
export const EMAIL_ID = 'Email Id'
export const PASSWORD_FIELD = 'passwordField';
export const PASSWORD_BLANK_VALIDATION_MSG = 'Please enter your password';
export const PASSWORD_REGEX_VALIDATION_MSG = 'Password must contain letters and numbers';
export const PASSWORD = 'Password';
export const TITLE_FIELD = 'titleField';
export const TITLE = 'Title';
export const TITLE_BLANK_VALIDATION_MSG = 'Please enter Title';
export const TITLE_REGEX_VALIDATION_MSG = 'Title must contain only letters';